port = 8081
maxThreadsCount = 64
failIfMappedDirectoryNotExists = true
generateIndexPage = true

[[mapping]]
browserPath = "/somePath"
fsPath = "/file/system/path"
allowFileUploading = true

[[mapping]]
browserPath = "/some/other/Path"
fsPath = "/file/system/other/path"